#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program pauses for 2 seconds

file=/tmp/my_process

while true; do
	sudo -c 'echo "I am alive!" >> $file'
	sleep 2
done
