#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# Only display "username", "user id", "home directory path for user"

while read -r passwd;  do
	echo "$passwd" | cut -d ":" -f1,3,6
done < "/etc/passwd"
