#!/usr/bin/env bash
# prints best school 10 times, but for 9th iteration

counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
