#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed

files=$(ls)

for file in $files;
do
	echo "$file" | cut -d '-' -f 2-
done
